# yaml-language-server: $schema=https://sap.github.io/ui5-tooling/schema/ui5.yaml.json

specVersion: "3.1"
metadata:
  name: sync.e05.deploy
type: application
builder:
  resources:
    excludes:
      - /test/**
      - /localService/**
  customTasks:
    - name: deploy-to-abap
      afterTask: generateCachebusterInfo
      configuration:
        target:
          url: HTTP://210.16.199.140:8001
          client: "100"
        app:
          name: YE05_UI5_TEST
          description: 전표조회
          package: ZEB_FI
          transport: KYSK903559
        exclude:
          - /test/
